language: ruby
rvm:
- 2.5.3
script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --http-status-ignore 999
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: 13bSXnjB2+dyOazu2RXjUpcjgjYOmfv2Bf5ihlnVO0Gcq3dXra+9UEQCx7xJVbz9ZCU/OC97gh4mPs2jGB3goVR3YdYrswvlQAwEAiSyaXK69Q6bDWp9hTfGXyTDfZj/RM6CwdFlrMYqK+JjGQP83TEEj0lOT6IWAs40AwiRfgEB0GqvDh7rjO2FIUcvwXMW/p5QKJtX+EABJvr0KqouHhukCJJD4X6ltBjPXs6PnOkPuTCC8LPYqJDX9iWB/5TVYZHA18Wzh6mYs32vZWN7PEFkQZsrJqrVOccL6RUw5k3x6PBhRhzeeODH0bMOETDrpoNz/7p7PmnleWjDHYKtzYHlASoPA9pQhc1OLcfgLQModQFHzelVfV3G7T0zSWkwEhxd2ejhwfmOK6RPQyX7R2TJKSn6YtvHxQb9fvc65YxXKyKHBoKZAmhZMVsDHbR3uPxE+U4uhrPW2GolijRt5fuLa/KWAQsUXaHzWUz5lPvSW3zS8mSc9QXjj9+I512bd840o7GkROayDzBVmeV205F3LvqPR++xX0HgSHlDjxjaWonfT6hggy9a8GC3ETxPkL2q6DKNK2N2WaVUVrxFEAI8e356sLnZ3g3OSFj1MqeFjdnwc1OjHjmvkN2gUD4aAn/yWB/I+ShKA6mhNkD7lKy+uR6m13TIR2Y7gI1tO4Q=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: false
