# Setup based on https://jekyllrb.com/docs/continuous-integration/travis-ci/

language: ruby
rvm:
  - 2.5.3

script: bundle exec jekyll build
# script: bundle exec jekyll build && bundle exec htmlproofer ./_site 
# Basic test (does it build):
# `jekyll build` builds a static site once for testing (`jekyll serve`
# builds static site that updates as changes are made for easier viewing)
# Advanced test (do things work):
# `htmlproofer ./_site` tests to make sure all links are functional, 
# things have tags, etc.

# Limiting tests to specified branches only, only for GitHub Pages
# Would test all branches otherwise
branches:
  only:
    - master
    # - gh-pages      # Test the gh-pages branch
    # - /pages-(.*)/  # Test every branch starting with "pages-"

# env:
#   global:
#     - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
#     # Nokogiri parses HTML files from compiled site and is bundled with libraries it needs to compile each time it's installed
#     # Speeds up installation of html-proofer

# addons:
#   apt:
#     packages:
#     - libcurl4-openssl-dev # Used to avoid SSL errors while testing

# sudo: false # Route your build to the container-based infrastructure for a faster build

# cache: bundler # Caching bundler gem packages will speed up build

# # # Optional: disable email notifications about the outcome of your builds
# # notifications:
# #   email: false