language: ruby
rvm:
  - 2.5.3
script:
  - echo $JEKYLL_GITHUB_TOKEN
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --http-status-ignore 999
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
  - secure: 2Gn7o29wvJCDwv+Vye1QwBUo9jlEPYXG1vy/MiRuGiWjy33LYYE39+2qxzcqUTwNuqkqsE/+aSRWlTbmfxDMjs81Wc8KlxipESpOJCjB2KHDezSlt95ySqNXOPcpQbmJEObILhJY881XkXl4OMELHdCpYtSTqzCpN7xRGi3uCzdyUUREBUH2exuOvmn8nBNno0CbJedRQ9lEcFAJHIkbxZbzaCrlFX+PrkbSImIhO6DEi25OgccR5iR38JElu55NTBLK9GILYPqQAW7oFV+d1nYeONIdtmmfWkwkO6Z12zIgKzJey1sVE3MVvPz+8Tc9plToZk1A1CBSFCeCLhtzzQHGq3s6iTALzuYgeVmj6RDHTO5P2qePwvbcp+zHWl2LuLxj/TIOVLKeqMoZRu15br2YAEaW6NhhoJMOOwuFz4Z3R5Bqr0LaICeMeQnXjyUDR8yT3SW3xVfMxPV80zNMx3LdZEYtb82ww5nqdHpypYvPXwPiaF5F55Xqk356kVpF4df7ZZugrIepz3+c++2g9sRQnwamM6NLwjTdcsKJvOT3aNUeiZ1MCa1Ia4mUALXoGWeCw0fHKwb9AIfwCUE5dJlPeZKIMHnrObRs5jRKEDmjQ1jck1kKpBg4YArSGC3CVruJKS5Ur1fsZvuwAmZLELJnlkeBNK4exJPa0lwU8gw=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: false
