language: ruby
rvm:
- 2.5.3
script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --http-status-ignore 999
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: g5zopHptG9uhNfL/TitKXl+i/G5Sqrc0sMSLLS9CtognBAk4IdaGolh6ECjjAlKB/ivMlisgArB33Xtt6Wpubig5oV28Y/B9yXQWHMfClxT8XMp12bPfVIhBWmfa+V+1dAP0OngN7BMqmJQrmYQgoOtlPH4b3yRjde6tbPmfCkcuJcGYT7Xv3RAP09eDeDenLVc+LIsKck10gv5PESfzq0zEX4VEgCPabbhr5XOqbQTF/QXBNdzie7xobIufXljvdgTxXSJ3avN9jtJiK3uHztZqXr0TV20LKS6biOQ39oJk9Qr7oE4rV9bybiPo6ckoaNfNQiMFPJ1WpG+f3IAqhWfji4fuAdHmYxSA27aHeaej2LxQiU2bK3XehLiFd68CZjcvf3U6DWQtwrYlSCxZ98oqrzL9lMQ6729VoF15OccTwPS3s7WKIzaqtPHU+rFykG/wZSPwy1/g5dpwdh3mnThrwXBebvNu8c2WIBqm6lBStB3Ijb1ofQUm7FgJQ6O9JDSA1kF1dnWduKx0FYhjj15JgGNkc5ODWkBYV1WadFxg23XmS7X6eZfDi/P+fHUhY392/4SWFlyQK4q389lHpoVA93Gw3oJZtpeaL+OylnJ9UFKwE+jpyry+0Am8UXQK7qUSQZPyEu3MBh5yg9t/rDgPJh3w6mvEiD2ZqhlNLbY=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$JEKYLL_GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
