language: ruby
rvm:
- 2.5.3
script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --http-status-ignore 999
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    secure: JxGcemiAGbNOHXljR99U7g5LC4Q+zWGwc3v+/asfuXD+P2m23maEdFp6UtBMnJPU1HTIt58OT9V6PXJd5QUE579vfoEfrIIPu4ttfdNT9cg7cyV5eJKRiNAlTJAxHYRddpovquxdukNKTOohFOolLwsRiHDSXbtzySPGXmONXU1qs3W7eHOvQiJYX6LW4r91uV8glUqM1OQ/20ypoXD4qvbJALP689jpKYK0hjB7AM3xVH8ITE3o9UQF/Ibsm+UFAvndNzIY8SBnrsnVposHqHyelxCQVYvmHoVyP2DuAxRBDA2z2nIZv6dF8PeTtaTnCNzGlytzD+GrbG5f3ZiIHakg81tJt7SZ1fO0pg/Fz5XPcyGqUkOk1NygRmoCOJORvFmkvt5dSd2NNbJK/MP+B1Y81xuMY02Routl0Zh9neI5Mn7sQ4MMxadD+dcUcI22VjD2l7pgD+rxU7XwfROClPPaZOca0IersXo7QpTiWPQHJn7M21LC7Qo5ddrNR8dnMBTszSrX0srkKLtI5VrJNmBc3a1y7GWX7UU1+ZSgN8x7dHBetBep6qsJA0n8rzl5PC7n79rsPHRTWuagnP1Op72Vijvx1A8NGLZ8o5FDww6p0vwHAC9NG2tKZkjTX5ctgq3sajaghwJx5hNnuQ0+MTVvT6bCx3XN4R2+Dm24eG4=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: false
